CC=gcc

stack-array: src/stack-array.c
	gcc -o dist/stack-array src/stack-array.c

stack-linkedlist: src/stack-linkedlist.c
	gcc -o dist/stack-linkedlist src/stack-linkedlist.c

linkedlist: src/linkedlist.h src/linkedlist.c
	gcc -o dist/linkedlist src/linkedlist.c

doublelinkedlist: src/doublelinkedlist.h src/doublelinkedlist.c
	gcc -o dist/doublelinkedlist src/doublelinkedlist.c

xorll: src/xorll.h src/xorll.c
	gcc -o dist/xorll src/xorll.c

circularlinkedlist: src/circularlinkedlist.h src/circularlinkedlist.c
	gcc -o dist/circularlinkedlist src/circularlinkedlist.c

binarySearchTree: src/binarySearchTree.h src/binarySearchTree.c
	gcc -o dist/binarySearchTree src/binarySearchTree.c

queue: src/queue.c
	gcc -o dist/queue queue.c

clean:
	rm dist/*