CC=gcc

stack-array: src/stack-array.c
	gcc -o dist/stack-array stack-array.c

stack-linkedlist: src/stack-linkedlist.c
	gcc -o dist/stack-linkedlist stack-linkedlist.c

linkedlist: src/linkedlist.h src/linkedlist.c
	gcc -o dist/linkedlist linkedlist.c

doublelinkedlist: src/doublelinkedlist.h src/doublelinkedlist.c
	gcc -o doublelinkedlist doublelinkedlist.c

binarySearchTree: src/binarySearchTree.h src/binarySearchTree.c
	gcc -o binarySearchTree binarySearchTree.c

xorll: src/xorll.h src/xorll.c
	gcc -o xorll xorll.c

queue: src/queue.c
	gcc -o queue queue.c

clean:
	rm dist/*